name: Deploy Vue
on:
  push:
    branches:
      - main
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        working-directory: ./umbraco-app
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: "jonasbeltoft"
          reponame: "umbraco-security-interview"
          token: ${{ secrets.GITHUB_TOKEN }}
